- Added test for 'value' property correct typing
webcomponents/custom-elements-everywhere pull request #552
Opened 2019-07-12 10:35 UTC by lmartorella

With web-component it will be common to write custom input selector widgets.
To follow the DOM standards, the 'value' property of custom widgets should work like other properties. In particular, the 'value' property should support non-string types as well (for example to implement a date selector widget).

We added then a specific test for the 'value' property, given we found an issue in VueJS about that: https://github.com/vuejs/vue/issues/10255
Only Vue seems to be affected by that.

2019-07-12 10:39 UTC, lmartorella commented
I signed it!

2021-03-24 11:37 UTC, sidharthramesh commented
Any updates?

2021-12-15 20:22 UTC, rictic requested changes
Thank you for the change!

Please rebase, update any new libraries, and run `npm run update-goldens` to update the expectedResults.json files to include this new test

2021-12-15 20:35 UTC, rictic commented
I'm also looking to add an assertion in `compareResultsAgainstGoldens` in /index.js of the number of tests to make sure we run the same number of tests in every library, so that will need to be updated too if that lands

2022-02-24 21:15 UTC, rictic commented
This is a good change! If you do get around to rebasing it to main, please reopen as a new PR

2022-02-24 21:15 UTC, closed without merging