Make libraries' build & test cross-platform
webcomponents/custom-elements-everywhere pull request #96
Opened 2017-10-18 21:09 UTC by bdukes

The build scripts for each library didn't work on Windows, so I replaced the *nix commands with equivalents from npm.

This does not address the top-level package's _build_ script, which is a bit more involved.  This can at least get people unstuck, and I'm looking into create a node script to run in place of the current _build_ script (since there didn't appear to be a simple replacement for `x & y & z & wait; kill $(jobs -p); … echo "" && exit 0`)

2017-10-19 04:21 UTC, robdodson commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-10-19 04:24 UTC, robdodson commented
I'll sort out those travis failures and try to follow up tomorrow. Thanks for sending this in!

2021-12-15 20:41 UTC, rictic requested changes
This seems like a good change. Needs a rebase I think, and to extend the test github action to run on windows as well as ubuntu

2022-02-24 21:15 UTC, rictic commented
This is a good change! If you do get around to rebasing it, please open a new PR

2022-02-24 21:15 UTC, closed without merging